---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: spines
  tasks:

    - name: Merge provided configuration with device configuration
      arista.eos.eos_interfaces:
        config:
          - name: Ethernet2
            enabled: true
            mode: layer3
          - name: Ethernet3
            enabled: true
            mode: layer3
          - name: Ethernet4
            enabled: true
            mode: layer3
          - name: Ethernet5
            enabled: true
            mode: layer3
        state: merged

    - name: Merge provided configuration with device configuration.
      arista.eos.eos_l2_interfaces:
        config:
          - name: Ethernet1
            mode: trunk
            trunk:
              native_vlan: 10
          - name: Ethernet2
            mode: access
            access:
              vlan: 30
        state: merged